# Generated by Django 4.1.7 on 2024-06-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10000)),
                ('place', models.CharField(default=None, max_length=1000)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(default=None, max_length=1000000000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10000)),
                ('length', models.IntegerField()),
                ('month_start', models.IntegerField()),
                ('day_start', models.IntegerField()),
                ('hour_start', models.IntegerField()),
                ('minute_start', models.IntegerField()),
                ('periodicity', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price_adult', models.IntegerField()),
                ('price_children', models.IntegerField()),
                ('price_invalid', models.IntegerField()),
                ('discount_price_adult', models.IntegerField()),
                ('discount_price_invalid', models.IntegerField()),
                ('discount_price_children', models.IntegerField()),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('gmail', models.CharField(default=None, max_length=100, null=True)),
                ('telephone', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.IntegerField()),
                ('children_count', models.IntegerField()),
                ('invalid_count', models.IntegerField()),
                ('programm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.programm')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.userinfo')),
            ],
        ),
    ]
