# Generated by Django 4.1.7 on 2024-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_place_image1_alter_place_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image2',
        ),
    ]
