# Generated by Django 4.1.7 on 2024-06-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_favorite_user_id_remove_registr_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='place_id',
            new_name='place',
        ),
    ]
