# Generated by Django 4.1.7 on 2024-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_rename_place_id_favorite_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='registr',
            name='status',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
